# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-03 16:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelplan_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdb',
            old_name='email',
            new_name='username',
        ),
    ]
