# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-03 17:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travelplan_app', '0002_auto_20170603_1619'),
    ]

    operations = [
        migrations.CreateModel(
            name='travelplan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('traveldate_from', models.DateField()),
                ('traveldate_to', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_travel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel_user', to='travelplan_app.userDB')),
            ],
        ),
        migrations.CreateModel(
            name='trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('travel_join', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_travel', to='travelplan_app.userDB')),
                ('user_trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_user', to='travelplan_app.userDB')),
            ],
        ),
    ]
