# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-03 21:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travelplan_app', '0003_travelplan_trip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='travel_join',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_travel', to='travelplan_app.travelplan'),
        ),
    ]
